package jp.co.siam.restapi.entity;

import java.util.Date;

public class Code {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.BusinessId
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CodeName
     *
     * @mbg.generated
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CodeLv1
     *
     * @mbg.generated
     */
    private String codeLv1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CodeLv2
     *
     * @mbg.generated
     */
    private String codeLv2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.Value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.DisplayText
     *
     * @mbg.generated
     */
    private String displayText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.DisplayOrder
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CodeComment
     *
     * @mbg.generated
     */
    private String codeComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.DeleteFlag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CreatedBy
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.CreatedDate
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.UpdatedBy
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_CODE.UpdatedDate
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.BusinessId
     *
     * @return the value of M_CODE.BusinessId
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.BusinessId
     *
     * @param businessId the value for M_CODE.BusinessId
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CodeName
     *
     * @return the value of M_CODE.CodeName
     *
     * @mbg.generated
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CodeName
     *
     * @param codeName the value for M_CODE.CodeName
     *
     * @mbg.generated
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CodeLv1
     *
     * @return the value of M_CODE.CodeLv1
     *
     * @mbg.generated
     */
    public String getCodeLv1() {
        return codeLv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CodeLv1
     *
     * @param codeLv1 the value for M_CODE.CodeLv1
     *
     * @mbg.generated
     */
    public void setCodeLv1(String codeLv1) {
        this.codeLv1 = codeLv1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CodeLv2
     *
     * @return the value of M_CODE.CodeLv2
     *
     * @mbg.generated
     */
    public String getCodeLv2() {
        return codeLv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CodeLv2
     *
     * @param codeLv2 the value for M_CODE.CodeLv2
     *
     * @mbg.generated
     */
    public void setCodeLv2(String codeLv2) {
        this.codeLv2 = codeLv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.Value
     *
     * @return the value of M_CODE.Value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.Value
     *
     * @param value the value for M_CODE.Value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.DisplayText
     *
     * @return the value of M_CODE.DisplayText
     *
     * @mbg.generated
     */
    public String getDisplayText() {
        return displayText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.DisplayText
     *
     * @param displayText the value for M_CODE.DisplayText
     *
     * @mbg.generated
     */
    public void setDisplayText(String displayText) {
        this.displayText = displayText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.DisplayOrder
     *
     * @return the value of M_CODE.DisplayOrder
     *
     * @mbg.generated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.DisplayOrder
     *
     * @param displayOrder the value for M_CODE.DisplayOrder
     *
     * @mbg.generated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CodeComment
     *
     * @return the value of M_CODE.CodeComment
     *
     * @mbg.generated
     */
    public String getCodeComment() {
        return codeComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CodeComment
     *
     * @param codeComment the value for M_CODE.CodeComment
     *
     * @mbg.generated
     */
    public void setCodeComment(String codeComment) {
        this.codeComment = codeComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.DeleteFlag
     *
     * @return the value of M_CODE.DeleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.DeleteFlag
     *
     * @param deleteFlag the value for M_CODE.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CreatedBy
     *
     * @return the value of M_CODE.CreatedBy
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CreatedBy
     *
     * @param createdBy the value for M_CODE.CreatedBy
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.CreatedDate
     *
     * @return the value of M_CODE.CreatedDate
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.CreatedDate
     *
     * @param createdDate the value for M_CODE.CreatedDate
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.UpdatedBy
     *
     * @return the value of M_CODE.UpdatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.UpdatedBy
     *
     * @param updatedBy the value for M_CODE.UpdatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_CODE.UpdatedDate
     *
     * @return the value of M_CODE.UpdatedDate
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_CODE.UpdatedDate
     *
     * @param updatedDate the value for M_CODE.UpdatedDate
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Code other = (Code) that;
        return (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getCodeName() == null ? other.getCodeName() == null : this.getCodeName().equals(other.getCodeName()))
            && (this.getCodeLv1() == null ? other.getCodeLv1() == null : this.getCodeLv1().equals(other.getCodeLv1()))
            && (this.getCodeLv2() == null ? other.getCodeLv2() == null : this.getCodeLv2().equals(other.getCodeLv2()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
            && (this.getDisplayText() == null ? other.getDisplayText() == null : this.getDisplayText().equals(other.getDisplayText()))
            && (this.getDisplayOrder() == null ? other.getDisplayOrder() == null : this.getDisplayOrder().equals(other.getDisplayOrder()))
            && (this.getCodeComment() == null ? other.getCodeComment() == null : this.getCodeComment().equals(other.getCodeComment()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getCodeName() == null) ? 0 : getCodeName().hashCode());
        result = prime * result + ((getCodeLv1() == null) ? 0 : getCodeLv1().hashCode());
        result = prime * result + ((getCodeLv2() == null) ? 0 : getCodeLv2().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getDisplayText() == null) ? 0 : getDisplayText().hashCode());
        result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
        result = prime * result + ((getCodeComment() == null) ? 0 : getCodeComment().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        return result;
    }
}