package jp.co.siam.restapi.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmployeeinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public EmployeeinfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmployeeidIsNull() {
            addCriterion("EmployeeId is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeidIsNotNull() {
            addCriterion("EmployeeId is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeidEqualTo(String value) {
            addCriterion("EmployeeId =", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotEqualTo(String value) {
            addCriterion("EmployeeId <>", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidGreaterThan(String value) {
            addCriterion("EmployeeId >", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidGreaterThanOrEqualTo(String value) {
            addCriterion("EmployeeId >=", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidLessThan(String value) {
            addCriterion("EmployeeId <", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidLessThanOrEqualTo(String value) {
            addCriterion("EmployeeId <=", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidLike(String value) {
            addCriterion("EmployeeId like", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotLike(String value) {
            addCriterion("EmployeeId not like", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidIn(List<String> values) {
            addCriterion("EmployeeId in", values, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotIn(List<String> values) {
            addCriterion("EmployeeId not in", values, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidBetween(String value1, String value2) {
            addCriterion("EmployeeId between", value1, value2, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotBetween(String value1, String value2) {
            addCriterion("EmployeeId not between", value1, value2, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameIsNull() {
            addCriterion("EmployeeFirstName is null");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameIsNotNull() {
            addCriterion("EmployeeFirstName is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameEqualTo(String value) {
            addCriterion("EmployeeFirstName =", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameNotEqualTo(String value) {
            addCriterion("EmployeeFirstName <>", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameGreaterThan(String value) {
            addCriterion("EmployeeFirstName >", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("EmployeeFirstName >=", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameLessThan(String value) {
            addCriterion("EmployeeFirstName <", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameLessThanOrEqualTo(String value) {
            addCriterion("EmployeeFirstName <=", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameLike(String value) {
            addCriterion("EmployeeFirstName like", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameNotLike(String value) {
            addCriterion("EmployeeFirstName not like", value, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameIn(List<String> values) {
            addCriterion("EmployeeFirstName in", values, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameNotIn(List<String> values) {
            addCriterion("EmployeeFirstName not in", values, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameBetween(String value1, String value2) {
            addCriterion("EmployeeFirstName between", value1, value2, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeefirstnameNotBetween(String value1, String value2) {
            addCriterion("EmployeeFirstName not between", value1, value2, "employeefirstname");
            return (Criteria) this;
        }

        public Criteria andEmployeenameIsNull() {
            addCriterion("EmployeeName is null");
            return (Criteria) this;
        }

        public Criteria andEmployeenameIsNotNull() {
            addCriterion("EmployeeName is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeenameEqualTo(String value) {
            addCriterion("EmployeeName =", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameNotEqualTo(String value) {
            addCriterion("EmployeeName <>", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameGreaterThan(String value) {
            addCriterion("EmployeeName >", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameGreaterThanOrEqualTo(String value) {
            addCriterion("EmployeeName >=", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameLessThan(String value) {
            addCriterion("EmployeeName <", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameLessThanOrEqualTo(String value) {
            addCriterion("EmployeeName <=", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameLike(String value) {
            addCriterion("EmployeeName like", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameNotLike(String value) {
            addCriterion("EmployeeName not like", value, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameIn(List<String> values) {
            addCriterion("EmployeeName in", values, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameNotIn(List<String> values) {
            addCriterion("EmployeeName not in", values, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameBetween(String value1, String value2) {
            addCriterion("EmployeeName between", value1, value2, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeenameNotBetween(String value1, String value2) {
            addCriterion("EmployeeName not between", value1, value2, "employeename");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekIsNull() {
            addCriterion("EmployeeFamilyNameK is null");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekIsNotNull() {
            addCriterion("EmployeeFamilyNameK is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekEqualTo(String value) {
            addCriterion("EmployeeFamilyNameK =", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekNotEqualTo(String value) {
            addCriterion("EmployeeFamilyNameK <>", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekGreaterThan(String value) {
            addCriterion("EmployeeFamilyNameK >", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekGreaterThanOrEqualTo(String value) {
            addCriterion("EmployeeFamilyNameK >=", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekLessThan(String value) {
            addCriterion("EmployeeFamilyNameK <", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekLessThanOrEqualTo(String value) {
            addCriterion("EmployeeFamilyNameK <=", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekLike(String value) {
            addCriterion("EmployeeFamilyNameK like", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekNotLike(String value) {
            addCriterion("EmployeeFamilyNameK not like", value, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekIn(List<String> values) {
            addCriterion("EmployeeFamilyNameK in", values, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekNotIn(List<String> values) {
            addCriterion("EmployeeFamilyNameK not in", values, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekBetween(String value1, String value2) {
            addCriterion("EmployeeFamilyNameK between", value1, value2, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeefamilynamekNotBetween(String value1, String value2) {
            addCriterion("EmployeeFamilyNameK not between", value1, value2, "employeefamilynamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekIsNull() {
            addCriterion("EmployeeGivenNameK is null");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekIsNotNull() {
            addCriterion("EmployeeGivenNameK is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekEqualTo(String value) {
            addCriterion("EmployeeGivenNameK =", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekNotEqualTo(String value) {
            addCriterion("EmployeeGivenNameK <>", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekGreaterThan(String value) {
            addCriterion("EmployeeGivenNameK >", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekGreaterThanOrEqualTo(String value) {
            addCriterion("EmployeeGivenNameK >=", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekLessThan(String value) {
            addCriterion("EmployeeGivenNameK <", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekLessThanOrEqualTo(String value) {
            addCriterion("EmployeeGivenNameK <=", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekLike(String value) {
            addCriterion("EmployeeGivenNameK like", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekNotLike(String value) {
            addCriterion("EmployeeGivenNameK not like", value, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekIn(List<String> values) {
            addCriterion("EmployeeGivenNameK in", values, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekNotIn(List<String> values) {
            addCriterion("EmployeeGivenNameK not in", values, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekBetween(String value1, String value2) {
            addCriterion("EmployeeGivenNameK between", value1, value2, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andEmployeegivennamekNotBetween(String value1, String value2) {
            addCriterion("EmployeeGivenNameK not between", value1, value2, "employeegivennamek");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIsNull() {
            addCriterion("PhoneNumber is null");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIsNotNull() {
            addCriterion("PhoneNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenumberEqualTo(String value) {
            addCriterion("PhoneNumber =", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotEqualTo(String value) {
            addCriterion("PhoneNumber <>", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberGreaterThan(String value) {
            addCriterion("PhoneNumber >", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("PhoneNumber >=", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLessThan(String value) {
            addCriterion("PhoneNumber <", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLessThanOrEqualTo(String value) {
            addCriterion("PhoneNumber <=", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLike(String value) {
            addCriterion("PhoneNumber like", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotLike(String value) {
            addCriterion("PhoneNumber not like", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIn(List<String> values) {
            addCriterion("PhoneNumber in", values, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotIn(List<String> values) {
            addCriterion("PhoneNumber not in", values, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberBetween(String value1, String value2) {
            addCriterion("PhoneNumber between", value1, value2, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotBetween(String value1, String value2) {
            addCriterion("PhoneNumber not between", value1, value2, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("Email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("Email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("Email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("Email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("Email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("Email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("Email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("Email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("Email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("Email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("Email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("Email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("Email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("Birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("Birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("Birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("Birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("Birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("Birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeIsNull() {
            addCriterion("AddressPostCode is null");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeIsNotNull() {
            addCriterion("AddressPostCode is not null");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeEqualTo(String value) {
            addCriterion("AddressPostCode =", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeNotEqualTo(String value) {
            addCriterion("AddressPostCode <>", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeGreaterThan(String value) {
            addCriterion("AddressPostCode >", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("AddressPostCode >=", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeLessThan(String value) {
            addCriterion("AddressPostCode <", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeLessThanOrEqualTo(String value) {
            addCriterion("AddressPostCode <=", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeLike(String value) {
            addCriterion("AddressPostCode like", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeNotLike(String value) {
            addCriterion("AddressPostCode not like", value, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeIn(List<String> values) {
            addCriterion("AddressPostCode in", values, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeNotIn(List<String> values) {
            addCriterion("AddressPostCode not in", values, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeBetween(String value1, String value2) {
            addCriterion("AddressPostCode between", value1, value2, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddresspostcodeNotBetween(String value1, String value2) {
            addCriterion("AddressPostCode not between", value1, value2, "addresspostcode");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureIsNull() {
            addCriterion("AddressPrefecture is null");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureIsNotNull() {
            addCriterion("AddressPrefecture is not null");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureEqualTo(String value) {
            addCriterion("AddressPrefecture =", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureNotEqualTo(String value) {
            addCriterion("AddressPrefecture <>", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureGreaterThan(String value) {
            addCriterion("AddressPrefecture >", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureGreaterThanOrEqualTo(String value) {
            addCriterion("AddressPrefecture >=", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureLessThan(String value) {
            addCriterion("AddressPrefecture <", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureLessThanOrEqualTo(String value) {
            addCriterion("AddressPrefecture <=", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureLike(String value) {
            addCriterion("AddressPrefecture like", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureNotLike(String value) {
            addCriterion("AddressPrefecture not like", value, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureIn(List<String> values) {
            addCriterion("AddressPrefecture in", values, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureNotIn(List<String> values) {
            addCriterion("AddressPrefecture not in", values, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureBetween(String value1, String value2) {
            addCriterion("AddressPrefecture between", value1, value2, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressprefectureNotBetween(String value1, String value2) {
            addCriterion("AddressPrefecture not between", value1, value2, "addressprefecture");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesIsNull() {
            addCriterion("AddressMunicipalities is null");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesIsNotNull() {
            addCriterion("AddressMunicipalities is not null");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesEqualTo(String value) {
            addCriterion("AddressMunicipalities =", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesNotEqualTo(String value) {
            addCriterion("AddressMunicipalities <>", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesGreaterThan(String value) {
            addCriterion("AddressMunicipalities >", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesGreaterThanOrEqualTo(String value) {
            addCriterion("AddressMunicipalities >=", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesLessThan(String value) {
            addCriterion("AddressMunicipalities <", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesLessThanOrEqualTo(String value) {
            addCriterion("AddressMunicipalities <=", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesLike(String value) {
            addCriterion("AddressMunicipalities like", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesNotLike(String value) {
            addCriterion("AddressMunicipalities not like", value, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesIn(List<String> values) {
            addCriterion("AddressMunicipalities in", values, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesNotIn(List<String> values) {
            addCriterion("AddressMunicipalities not in", values, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesBetween(String value1, String value2) {
            addCriterion("AddressMunicipalities between", value1, value2, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressmunicipalitiesNotBetween(String value1, String value2) {
            addCriterion("AddressMunicipalities not between", value1, value2, "addressmunicipalities");
            return (Criteria) this;
        }

        public Criteria andAddressotherIsNull() {
            addCriterion("AddressOther is null");
            return (Criteria) this;
        }

        public Criteria andAddressotherIsNotNull() {
            addCriterion("AddressOther is not null");
            return (Criteria) this;
        }

        public Criteria andAddressotherEqualTo(String value) {
            addCriterion("AddressOther =", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherNotEqualTo(String value) {
            addCriterion("AddressOther <>", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherGreaterThan(String value) {
            addCriterion("AddressOther >", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherGreaterThanOrEqualTo(String value) {
            addCriterion("AddressOther >=", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherLessThan(String value) {
            addCriterion("AddressOther <", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherLessThanOrEqualTo(String value) {
            addCriterion("AddressOther <=", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherLike(String value) {
            addCriterion("AddressOther like", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherNotLike(String value) {
            addCriterion("AddressOther not like", value, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherIn(List<String> values) {
            addCriterion("AddressOther in", values, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherNotIn(List<String> values) {
            addCriterion("AddressOther not in", values, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherBetween(String value1, String value2) {
            addCriterion("AddressOther between", value1, value2, "addressother");
            return (Criteria) this;
        }

        public Criteria andAddressotherNotBetween(String value1, String value2) {
            addCriterion("AddressOther not between", value1, value2, "addressother");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateIsNull() {
            addCriterion("EmploymentDate is null");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateIsNotNull() {
            addCriterion("EmploymentDate is not null");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateEqualTo(Date value) {
            addCriterionForJDBCDate("EmploymentDate =", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EmploymentDate <>", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateGreaterThan(Date value) {
            addCriterionForJDBCDate("EmploymentDate >", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EmploymentDate >=", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateLessThan(Date value) {
            addCriterionForJDBCDate("EmploymentDate <", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EmploymentDate <=", value, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateIn(List<Date> values) {
            addCriterionForJDBCDate("EmploymentDate in", values, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EmploymentDate not in", values, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EmploymentDate between", value1, value2, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andEmploymentdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EmploymentDate not between", value1, value2, "employmentdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateIsNull() {
            addCriterion("TerminationDate is null");
            return (Criteria) this;
        }

        public Criteria andTerminationdateIsNotNull() {
            addCriterion("TerminationDate is not null");
            return (Criteria) this;
        }

        public Criteria andTerminationdateEqualTo(Date value) {
            addCriterionForJDBCDate("TerminationDate =", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("TerminationDate <>", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateGreaterThan(Date value) {
            addCriterionForJDBCDate("TerminationDate >", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TerminationDate >=", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateLessThan(Date value) {
            addCriterionForJDBCDate("TerminationDate <", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TerminationDate <=", value, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateIn(List<Date> values) {
            addCriterionForJDBCDate("TerminationDate in", values, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("TerminationDate not in", values, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TerminationDate between", value1, value2, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andTerminationdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TerminationDate not between", value1, value2, "terminationdate");
            return (Criteria) this;
        }

        public Criteria andRankidIsNull() {
            addCriterion("RankId is null");
            return (Criteria) this;
        }

        public Criteria andRankidIsNotNull() {
            addCriterion("RankId is not null");
            return (Criteria) this;
        }

        public Criteria andRankidEqualTo(String value) {
            addCriterion("RankId =", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidNotEqualTo(String value) {
            addCriterion("RankId <>", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidGreaterThan(String value) {
            addCriterion("RankId >", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidGreaterThanOrEqualTo(String value) {
            addCriterion("RankId >=", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidLessThan(String value) {
            addCriterion("RankId <", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidLessThanOrEqualTo(String value) {
            addCriterion("RankId <=", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidLike(String value) {
            addCriterion("RankId like", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidNotLike(String value) {
            addCriterion("RankId not like", value, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidIn(List<String> values) {
            addCriterion("RankId in", values, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidNotIn(List<String> values) {
            addCriterion("RankId not in", values, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidBetween(String value1, String value2) {
            addCriterion("RankId between", value1, value2, "rankid");
            return (Criteria) this;
        }

        public Criteria andRankidNotBetween(String value1, String value2) {
            addCriterion("RankId not between", value1, value2, "rankid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidIsNull() {
            addCriterion("IntroducerEmployeeId is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidIsNotNull() {
            addCriterion("IntroducerEmployeeId is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidEqualTo(String value) {
            addCriterion("IntroducerEmployeeId =", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidNotEqualTo(String value) {
            addCriterion("IntroducerEmployeeId <>", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidGreaterThan(String value) {
            addCriterion("IntroducerEmployeeId >", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidGreaterThanOrEqualTo(String value) {
            addCriterion("IntroducerEmployeeId >=", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidLessThan(String value) {
            addCriterion("IntroducerEmployeeId <", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidLessThanOrEqualTo(String value) {
            addCriterion("IntroducerEmployeeId <=", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidLike(String value) {
            addCriterion("IntroducerEmployeeId like", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidNotLike(String value) {
            addCriterion("IntroducerEmployeeId not like", value, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidIn(List<String> values) {
            addCriterion("IntroducerEmployeeId in", values, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidNotIn(List<String> values) {
            addCriterion("IntroducerEmployeeId not in", values, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidBetween(String value1, String value2) {
            addCriterion("IntroducerEmployeeId between", value1, value2, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andIntroduceremployeeidNotBetween(String value1, String value2) {
            addCriterion("IntroducerEmployeeId not between", value1, value2, "introduceremployeeid");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusIsNull() {
            addCriterion("EmploymentStatus is null");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusIsNotNull() {
            addCriterion("EmploymentStatus is not null");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusEqualTo(Integer value) {
            addCriterion("EmploymentStatus =", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusNotEqualTo(Integer value) {
            addCriterion("EmploymentStatus <>", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusGreaterThan(Integer value) {
            addCriterion("EmploymentStatus >", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("EmploymentStatus >=", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusLessThan(Integer value) {
            addCriterion("EmploymentStatus <", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusLessThanOrEqualTo(Integer value) {
            addCriterion("EmploymentStatus <=", value, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusIn(List<Integer> values) {
            addCriterion("EmploymentStatus in", values, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusNotIn(List<Integer> values) {
            addCriterion("EmploymentStatus not in", values, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusBetween(Integer value1, Integer value2) {
            addCriterion("EmploymentStatus between", value1, value2, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andEmploymentstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("EmploymentStatus not between", value1, value2, "employmentstatus");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("RoleId is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("RoleId is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(String value) {
            addCriterion("RoleId =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(String value) {
            addCriterion("RoleId <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(String value) {
            addCriterion("RoleId >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("RoleId >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(String value) {
            addCriterion("RoleId <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(String value) {
            addCriterion("RoleId <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLike(String value) {
            addCriterion("RoleId like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotLike(String value) {
            addCriterion("RoleId not like", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<String> values) {
            addCriterion("RoleId in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<String> values) {
            addCriterion("RoleId not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(String value1, String value2) {
            addCriterion("RoleId between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(String value1, String value2) {
            addCriterion("RoleId not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("Remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("Remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("Remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("Remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("Remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("Remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("Remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("Remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("Remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("Remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("Remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("Remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("Remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("Remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("DeleteFlag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("DeleteFlag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Integer value) {
            addCriterion("DeleteFlag =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Integer value) {
            addCriterion("DeleteFlag <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Integer value) {
            addCriterion("DeleteFlag >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DeleteFlag >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Integer value) {
            addCriterion("DeleteFlag <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Integer value) {
            addCriterion("DeleteFlag <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Integer> values) {
            addCriterion("DeleteFlag in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Integer> values) {
            addCriterion("DeleteFlag not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Integer value1, Integer value2) {
            addCriterion("DeleteFlag between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Integer value1, Integer value2) {
            addCriterion("DeleteFlag not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("CreatedBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("CreatedBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("CreatedBy =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("CreatedBy <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("CreatedBy >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedBy >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("CreatedBy <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("CreatedBy <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("CreatedBy like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("CreatedBy not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("CreatedBy in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("CreatedBy not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("CreatedBy between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("CreatedBy not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("CreatedDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("CreatedDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterionForJDBCDate("CreatedDate =", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CreatedDate <>", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterionForJDBCDate("CreatedDate >", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CreatedDate >=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterionForJDBCDate("CreatedDate <", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CreatedDate <=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterionForJDBCDate("CreatedDate in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("CreatedDate not in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CreatedDate between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CreatedDate not between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyIsNull() {
            addCriterion("UpdatedBy is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyIsNotNull() {
            addCriterion("UpdatedBy is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyEqualTo(String value) {
            addCriterion("UpdatedBy =", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyNotEqualTo(String value) {
            addCriterion("UpdatedBy <>", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyGreaterThan(String value) {
            addCriterion("UpdatedBy >", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("UpdatedBy >=", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyLessThan(String value) {
            addCriterion("UpdatedBy <", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyLessThanOrEqualTo(String value) {
            addCriterion("UpdatedBy <=", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyLike(String value) {
            addCriterion("UpdatedBy like", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyNotLike(String value) {
            addCriterion("UpdatedBy not like", value, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyIn(List<String> values) {
            addCriterion("UpdatedBy in", values, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyNotIn(List<String> values) {
            addCriterion("UpdatedBy not in", values, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyBetween(String value1, String value2) {
            addCriterion("UpdatedBy between", value1, value2, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdatedbyNotBetween(String value1, String value2) {
            addCriterion("UpdatedBy not between", value1, value2, "updatedby");
            return (Criteria) this;
        }

        public Criteria andUpdateddateIsNull() {
            addCriterion("UpdatedDate is null");
            return (Criteria) this;
        }

        public Criteria andUpdateddateIsNotNull() {
            addCriterion("UpdatedDate is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateddateEqualTo(Date value) {
            addCriterionForJDBCDate("UpdatedDate =", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("UpdatedDate <>", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateGreaterThan(Date value) {
            addCriterionForJDBCDate("UpdatedDate >", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UpdatedDate >=", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateLessThan(Date value) {
            addCriterionForJDBCDate("UpdatedDate <", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UpdatedDate <=", value, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateIn(List<Date> values) {
            addCriterionForJDBCDate("UpdatedDate in", values, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("UpdatedDate not in", values, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UpdatedDate between", value1, value2, "updateddate");
            return (Criteria) this;
        }

        public Criteria andUpdateddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UpdatedDate not between", value1, value2, "updateddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}