package jp.co.siam.restapi.entity;

import java.util.Date;

public class Employeeinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmployeeId
     *
     * @mbg.generated
     */
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmployeeFirstName
     *
     * @mbg.generated
     */
    private String employeefirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmployeeName
     *
     * @mbg.generated
     */
    private String employeename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmployeeFamilyNameK
     *
     * @mbg.generated
     */
    private String employeefamilynamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmployeeGivenNameK
     *
     * @mbg.generated
     */
    private String employeegivennamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.Sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.PhoneNumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.Birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.AddressPostCode
     *
     * @mbg.generated
     */
    private String addresspostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    private String addressprefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    private String addressmunicipalities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.AddressOther
     *
     * @mbg.generated
     */
    private String addressother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmploymentDate
     *
     * @mbg.generated
     */
    private Date employmentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.TerminationDate
     *
     * @mbg.generated
     */
    private Date terminationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.RankId
     *
     * @mbg.generated
     */
    private String rankid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.IntroducerEmployeeId
     *
     * @mbg.generated
     */
    private String introduceremployeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.EmploymentStatus
     *
     * @mbg.generated
     */
    private Integer employmentstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.Password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.RoleId
     *
     * @mbg.generated
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.DeleteFlag
     *
     * @mbg.generated
     */
    private Integer deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.CreatedBy
     *
     * @mbg.generated
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.CreatedDate
     *
     * @mbg.generated
     */
    private Date createddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.UpdatedBy
     *
     * @mbg.generated
     */
    private String updatedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_EmployeeInfo.UpdatedDate
     *
     * @mbg.generated
     */
    private Date updateddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmployeeId
     *
     * @return the value of M_EmployeeInfo.EmployeeId
     *
     * @mbg.generated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmployeeId
     *
     * @param employeeid the value for M_EmployeeInfo.EmployeeId
     *
     * @mbg.generated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmployeeFirstName
     *
     * @return the value of M_EmployeeInfo.EmployeeFirstName
     *
     * @mbg.generated
     */
    public String getEmployeefirstname() {
        return employeefirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmployeeFirstName
     *
     * @param employeefirstname the value for M_EmployeeInfo.EmployeeFirstName
     *
     * @mbg.generated
     */
    public void setEmployeefirstname(String employeefirstname) {
        this.employeefirstname = employeefirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmployeeName
     *
     * @return the value of M_EmployeeInfo.EmployeeName
     *
     * @mbg.generated
     */
    public String getEmployeename() {
        return employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmployeeName
     *
     * @param employeename the value for M_EmployeeInfo.EmployeeName
     *
     * @mbg.generated
     */
    public void setEmployeename(String employeename) {
        this.employeename = employeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmployeeFamilyNameK
     *
     * @return the value of M_EmployeeInfo.EmployeeFamilyNameK
     *
     * @mbg.generated
     */
    public String getEmployeefamilynamek() {
        return employeefamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmployeeFamilyNameK
     *
     * @param employeefamilynamek the value for M_EmployeeInfo.EmployeeFamilyNameK
     *
     * @mbg.generated
     */
    public void setEmployeefamilynamek(String employeefamilynamek) {
        this.employeefamilynamek = employeefamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmployeeGivenNameK
     *
     * @return the value of M_EmployeeInfo.EmployeeGivenNameK
     *
     * @mbg.generated
     */
    public String getEmployeegivennamek() {
        return employeegivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmployeeGivenNameK
     *
     * @param employeegivennamek the value for M_EmployeeInfo.EmployeeGivenNameK
     *
     * @mbg.generated
     */
    public void setEmployeegivennamek(String employeegivennamek) {
        this.employeegivennamek = employeegivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.Sex
     *
     * @return the value of M_EmployeeInfo.Sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.Sex
     *
     * @param sex the value for M_EmployeeInfo.Sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.PhoneNumber
     *
     * @return the value of M_EmployeeInfo.PhoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.PhoneNumber
     *
     * @param phonenumber the value for M_EmployeeInfo.PhoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.Email
     *
     * @return the value of M_EmployeeInfo.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.Email
     *
     * @param email the value for M_EmployeeInfo.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.Birthday
     *
     * @return the value of M_EmployeeInfo.Birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.Birthday
     *
     * @param birthday the value for M_EmployeeInfo.Birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.AddressPostCode
     *
     * @return the value of M_EmployeeInfo.AddressPostCode
     *
     * @mbg.generated
     */
    public String getAddresspostcode() {
        return addresspostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.AddressPostCode
     *
     * @param addresspostcode the value for M_EmployeeInfo.AddressPostCode
     *
     * @mbg.generated
     */
    public void setAddresspostcode(String addresspostcode) {
        this.addresspostcode = addresspostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.AddressPrefecture
     *
     * @return the value of M_EmployeeInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    public String getAddressprefecture() {
        return addressprefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.AddressPrefecture
     *
     * @param addressprefecture the value for M_EmployeeInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    public void setAddressprefecture(String addressprefecture) {
        this.addressprefecture = addressprefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.AddressMunicipalities
     *
     * @return the value of M_EmployeeInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    public String getAddressmunicipalities() {
        return addressmunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.AddressMunicipalities
     *
     * @param addressmunicipalities the value for M_EmployeeInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    public void setAddressmunicipalities(String addressmunicipalities) {
        this.addressmunicipalities = addressmunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.AddressOther
     *
     * @return the value of M_EmployeeInfo.AddressOther
     *
     * @mbg.generated
     */
    public String getAddressother() {
        return addressother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.AddressOther
     *
     * @param addressother the value for M_EmployeeInfo.AddressOther
     *
     * @mbg.generated
     */
    public void setAddressother(String addressother) {
        this.addressother = addressother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmploymentDate
     *
     * @return the value of M_EmployeeInfo.EmploymentDate
     *
     * @mbg.generated
     */
    public Date getEmploymentdate() {
        return employmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmploymentDate
     *
     * @param employmentdate the value for M_EmployeeInfo.EmploymentDate
     *
     * @mbg.generated
     */
    public void setEmploymentdate(Date employmentdate) {
        this.employmentdate = employmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.TerminationDate
     *
     * @return the value of M_EmployeeInfo.TerminationDate
     *
     * @mbg.generated
     */
    public Date getTerminationdate() {
        return terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.TerminationDate
     *
     * @param terminationdate the value for M_EmployeeInfo.TerminationDate
     *
     * @mbg.generated
     */
    public void setTerminationdate(Date terminationdate) {
        this.terminationdate = terminationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.RankId
     *
     * @return the value of M_EmployeeInfo.RankId
     *
     * @mbg.generated
     */
    public String getRankid() {
        return rankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.RankId
     *
     * @param rankid the value for M_EmployeeInfo.RankId
     *
     * @mbg.generated
     */
    public void setRankid(String rankid) {
        this.rankid = rankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.IntroducerEmployeeId
     *
     * @return the value of M_EmployeeInfo.IntroducerEmployeeId
     *
     * @mbg.generated
     */
    public String getIntroduceremployeeid() {
        return introduceremployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.IntroducerEmployeeId
     *
     * @param introduceremployeeid the value for M_EmployeeInfo.IntroducerEmployeeId
     *
     * @mbg.generated
     */
    public void setIntroduceremployeeid(String introduceremployeeid) {
        this.introduceremployeeid = introduceremployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.EmploymentStatus
     *
     * @return the value of M_EmployeeInfo.EmploymentStatus
     *
     * @mbg.generated
     */
    public Integer getEmploymentstatus() {
        return employmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.EmploymentStatus
     *
     * @param employmentstatus the value for M_EmployeeInfo.EmploymentStatus
     *
     * @mbg.generated
     */
    public void setEmploymentstatus(Integer employmentstatus) {
        this.employmentstatus = employmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.Password
     *
     * @return the value of M_EmployeeInfo.Password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.Password
     *
     * @param password the value for M_EmployeeInfo.Password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.RoleId
     *
     * @return the value of M_EmployeeInfo.RoleId
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.RoleId
     *
     * @param roleid the value for M_EmployeeInfo.RoleId
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.Remarks
     *
     * @return the value of M_EmployeeInfo.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.Remarks
     *
     * @param remarks the value for M_EmployeeInfo.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.DeleteFlag
     *
     * @return the value of M_EmployeeInfo.DeleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.DeleteFlag
     *
     * @param deleteflag the value for M_EmployeeInfo.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.CreatedBy
     *
     * @return the value of M_EmployeeInfo.CreatedBy
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.CreatedBy
     *
     * @param createdby the value for M_EmployeeInfo.CreatedBy
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.CreatedDate
     *
     * @return the value of M_EmployeeInfo.CreatedDate
     *
     * @mbg.generated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.CreatedDate
     *
     * @param createddate the value for M_EmployeeInfo.CreatedDate
     *
     * @mbg.generated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.UpdatedBy
     *
     * @return the value of M_EmployeeInfo.UpdatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.UpdatedBy
     *
     * @param updatedby the value for M_EmployeeInfo.UpdatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_EmployeeInfo.UpdatedDate
     *
     * @return the value of M_EmployeeInfo.UpdatedDate
     *
     * @mbg.generated
     */
    public Date getUpdateddate() {
        return updateddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_EmployeeInfo.UpdatedDate
     *
     * @param updateddate the value for M_EmployeeInfo.UpdatedDate
     *
     * @mbg.generated
     */
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Employeeinfo other = (Employeeinfo) that;
        return (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getEmployeefirstname() == null ? other.getEmployeefirstname() == null : this.getEmployeefirstname().equals(other.getEmployeefirstname()))
            && (this.getEmployeename() == null ? other.getEmployeename() == null : this.getEmployeename().equals(other.getEmployeename()))
            && (this.getEmployeefamilynamek() == null ? other.getEmployeefamilynamek() == null : this.getEmployeefamilynamek().equals(other.getEmployeefamilynamek()))
            && (this.getEmployeegivennamek() == null ? other.getEmployeegivennamek() == null : this.getEmployeegivennamek().equals(other.getEmployeegivennamek()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPhonenumber() == null ? other.getPhonenumber() == null : this.getPhonenumber().equals(other.getPhonenumber()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAddresspostcode() == null ? other.getAddresspostcode() == null : this.getAddresspostcode().equals(other.getAddresspostcode()))
            && (this.getAddressprefecture() == null ? other.getAddressprefecture() == null : this.getAddressprefecture().equals(other.getAddressprefecture()))
            && (this.getAddressmunicipalities() == null ? other.getAddressmunicipalities() == null : this.getAddressmunicipalities().equals(other.getAddressmunicipalities()))
            && (this.getAddressother() == null ? other.getAddressother() == null : this.getAddressother().equals(other.getAddressother()))
            && (this.getEmploymentdate() == null ? other.getEmploymentdate() == null : this.getEmploymentdate().equals(other.getEmploymentdate()))
            && (this.getTerminationdate() == null ? other.getTerminationdate() == null : this.getTerminationdate().equals(other.getTerminationdate()))
            && (this.getRankid() == null ? other.getRankid() == null : this.getRankid().equals(other.getRankid()))
            && (this.getIntroduceremployeeid() == null ? other.getIntroduceremployeeid() == null : this.getIntroduceremployeeid().equals(other.getIntroduceremployeeid()))
            && (this.getEmploymentstatus() == null ? other.getEmploymentstatus() == null : this.getEmploymentstatus().equals(other.getEmploymentstatus()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDeleteflag() == null ? other.getDeleteflag() == null : this.getDeleteflag().equals(other.getDeleteflag()))
            && (this.getCreatedby() == null ? other.getCreatedby() == null : this.getCreatedby().equals(other.getCreatedby()))
            && (this.getCreateddate() == null ? other.getCreateddate() == null : this.getCreateddate().equals(other.getCreateddate()))
            && (this.getUpdatedby() == null ? other.getUpdatedby() == null : this.getUpdatedby().equals(other.getUpdatedby()))
            && (this.getUpdateddate() == null ? other.getUpdateddate() == null : this.getUpdateddate().equals(other.getUpdateddate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getEmployeefirstname() == null) ? 0 : getEmployeefirstname().hashCode());
        result = prime * result + ((getEmployeename() == null) ? 0 : getEmployeename().hashCode());
        result = prime * result + ((getEmployeefamilynamek() == null) ? 0 : getEmployeefamilynamek().hashCode());
        result = prime * result + ((getEmployeegivennamek() == null) ? 0 : getEmployeegivennamek().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPhonenumber() == null) ? 0 : getPhonenumber().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAddresspostcode() == null) ? 0 : getAddresspostcode().hashCode());
        result = prime * result + ((getAddressprefecture() == null) ? 0 : getAddressprefecture().hashCode());
        result = prime * result + ((getAddressmunicipalities() == null) ? 0 : getAddressmunicipalities().hashCode());
        result = prime * result + ((getAddressother() == null) ? 0 : getAddressother().hashCode());
        result = prime * result + ((getEmploymentdate() == null) ? 0 : getEmploymentdate().hashCode());
        result = prime * result + ((getTerminationdate() == null) ? 0 : getTerminationdate().hashCode());
        result = prime * result + ((getRankid() == null) ? 0 : getRankid().hashCode());
        result = prime * result + ((getIntroduceremployeeid() == null) ? 0 : getIntroduceremployeeid().hashCode());
        result = prime * result + ((getEmploymentstatus() == null) ? 0 : getEmploymentstatus().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDeleteflag() == null) ? 0 : getDeleteflag().hashCode());
        result = prime * result + ((getCreatedby() == null) ? 0 : getCreatedby().hashCode());
        result = prime * result + ((getCreateddate() == null) ? 0 : getCreateddate().hashCode());
        result = prime * result + ((getUpdatedby() == null) ? 0 : getUpdatedby().hashCode());
        result = prime * result + ((getUpdateddate() == null) ? 0 : getUpdateddate().hashCode());
        return result;
    }
}