package jp.co.siam.restapi.entity;

import java.util.Date;

public class Insuranceproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.ProductId
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.InsuranceCompanyId
     *
     * @mbg.generated
     */
    private String insuranceCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.InsuranceCompanyProductId
     *
     * @mbg.generated
     */
    private String insuranceCompanyProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.ProductName
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.StartDate
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.EndDate
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.SaleStatus
     *
     * @mbg.generated
     */
    private Integer saleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.DeleteFlag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.CreatedBy
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.CreatedDate
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.UpdatedBy
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceProduct.UpdatedDate
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.ProductId
     *
     * @return the value of M_InsuranceProduct.ProductId
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.ProductId
     *
     * @param productId the value for M_InsuranceProduct.ProductId
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.InsuranceCompanyId
     *
     * @return the value of M_InsuranceProduct.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public String getInsuranceCompanyId() {
        return insuranceCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.InsuranceCompanyId
     *
     * @param insuranceCompanyId the value for M_InsuranceProduct.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public void setInsuranceCompanyId(String insuranceCompanyId) {
        this.insuranceCompanyId = insuranceCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.InsuranceCompanyProductId
     *
     * @return the value of M_InsuranceProduct.InsuranceCompanyProductId
     *
     * @mbg.generated
     */
    public String getInsuranceCompanyProductId() {
        return insuranceCompanyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.InsuranceCompanyProductId
     *
     * @param insuranceCompanyProductId the value for M_InsuranceProduct.InsuranceCompanyProductId
     *
     * @mbg.generated
     */
    public void setInsuranceCompanyProductId(String insuranceCompanyProductId) {
        this.insuranceCompanyProductId = insuranceCompanyProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.ProductName
     *
     * @return the value of M_InsuranceProduct.ProductName
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.ProductName
     *
     * @param productName the value for M_InsuranceProduct.ProductName
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.StartDate
     *
     * @return the value of M_InsuranceProduct.StartDate
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.StartDate
     *
     * @param startDate the value for M_InsuranceProduct.StartDate
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.EndDate
     *
     * @return the value of M_InsuranceProduct.EndDate
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.EndDate
     *
     * @param endDate the value for M_InsuranceProduct.EndDate
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.SaleStatus
     *
     * @return the value of M_InsuranceProduct.SaleStatus
     *
     * @mbg.generated
     */
    public Integer getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.SaleStatus
     *
     * @param saleStatus the value for M_InsuranceProduct.SaleStatus
     *
     * @mbg.generated
     */
    public void setSaleStatus(Integer saleStatus) {
        this.saleStatus = saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.Remarks
     *
     * @return the value of M_InsuranceProduct.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.Remarks
     *
     * @param remarks the value for M_InsuranceProduct.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.DeleteFlag
     *
     * @return the value of M_InsuranceProduct.DeleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.DeleteFlag
     *
     * @param deleteFlag the value for M_InsuranceProduct.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.CreatedBy
     *
     * @return the value of M_InsuranceProduct.CreatedBy
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.CreatedBy
     *
     * @param createdBy the value for M_InsuranceProduct.CreatedBy
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.CreatedDate
     *
     * @return the value of M_InsuranceProduct.CreatedDate
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.CreatedDate
     *
     * @param createdDate the value for M_InsuranceProduct.CreatedDate
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.UpdatedBy
     *
     * @return the value of M_InsuranceProduct.UpdatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.UpdatedBy
     *
     * @param updatedBy the value for M_InsuranceProduct.UpdatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceProduct.UpdatedDate
     *
     * @return the value of M_InsuranceProduct.UpdatedDate
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceProduct.UpdatedDate
     *
     * @param updatedDate the value for M_InsuranceProduct.UpdatedDate
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Insuranceproduct other = (Insuranceproduct) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getInsuranceCompanyId() == null ? other.getInsuranceCompanyId() == null : this.getInsuranceCompanyId().equals(other.getInsuranceCompanyId()))
            && (this.getInsuranceCompanyProductId() == null ? other.getInsuranceCompanyProductId() == null : this.getInsuranceCompanyProductId().equals(other.getInsuranceCompanyProductId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getSaleStatus() == null ? other.getSaleStatus() == null : this.getSaleStatus().equals(other.getSaleStatus()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getInsuranceCompanyId() == null) ? 0 : getInsuranceCompanyId().hashCode());
        result = prime * result + ((getInsuranceCompanyProductId() == null) ? 0 : getInsuranceCompanyProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getSaleStatus() == null) ? 0 : getSaleStatus().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        return result;
    }
}