package jp.co.siam.restapi.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
public class InsurancecontractinfoWithBLOBs extends Insurancecontractinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsurancePlanName
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "insuranceplanname")
    private String insuranceplanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerNameKana
     *
     * @mbg.generated
     */
    private String customernamekana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    private String relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredNameKana
     *
     * @mbg.generated
     */
    private String insurednamekana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredName
     *
     * @mbg.generated
     */
    private String insuredname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerBirthday
     *
     * @mbg.generated
     */
    private String customerbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    private String customerphonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerAddress
     *
     * @mbg.generated
     */
    private String customeraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerEmail
     *
     * @mbg.generated
     */
    private String customeremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractDetail
     *
     * @mbg.generated
     */
    private String contractdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    private String contractdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    private String employeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsurancePlanName
     *
     * @return the value of T_InsuranceContractInfo.InsurancePlanName
     *
     * @mbg.generated
     */
    public String getInsuranceplanname() {
        return insuranceplanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsurancePlanName
     *
     * @param insuranceplanname the value for T_InsuranceContractInfo.InsurancePlanName
     *
     * @mbg.generated
     */
    public void setInsuranceplanname(String insuranceplanname) {
        this.insuranceplanname = insuranceplanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerNameKana
     *
     * @return the value of T_InsuranceContractInfo.CustomerNameKana
     *
     * @mbg.generated
     */
    public String getCustomernamekana() {
        return customernamekana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerNameKana
     *
     * @param customernamekana the value for T_InsuranceContractInfo.CustomerNameKana
     *
     * @mbg.generated
     */
    public void setCustomernamekana(String customernamekana) {
        this.customernamekana = customernamekana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerName
     *
     * @return the value of T_InsuranceContractInfo.CustomerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerName
     *
     * @param customername the value for T_InsuranceContractInfo.CustomerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Relationship
     *
     * @return the value of T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Relationship
     *
     * @param relationship the value for T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredNameKana
     *
     * @return the value of T_InsuranceContractInfo.InsuredNameKana
     *
     * @mbg.generated
     */
    public String getInsurednamekana() {
        return insurednamekana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredNameKana
     *
     * @param insurednamekana the value for T_InsuranceContractInfo.InsuredNameKana
     *
     * @mbg.generated
     */
    public void setInsurednamekana(String insurednamekana) {
        this.insurednamekana = insurednamekana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredName
     *
     * @return the value of T_InsuranceContractInfo.InsuredName
     *
     * @mbg.generated
     */
    public String getInsuredname() {
        return insuredname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredName
     *
     * @param insuredname the value for T_InsuranceContractInfo.InsuredName
     *
     * @mbg.generated
     */
    public void setInsuredname(String insuredname) {
        this.insuredname = insuredname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerBirthday
     *
     * @return the value of T_InsuranceContractInfo.CustomerBirthday
     *
     * @mbg.generated
     */
    public String getCustomerbirthday() {
        return customerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerBirthday
     *
     * @param customerbirthday the value for T_InsuranceContractInfo.CustomerBirthday
     *
     * @mbg.generated
     */
    public void setCustomerbirthday(String customerbirthday) {
        this.customerbirthday = customerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerPhoneNumber
     *
     * @return the value of T_InsuranceContractInfo.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    public String getCustomerphonenumber() {
        return customerphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerPhoneNumber
     *
     * @param customerphonenumber the value for T_InsuranceContractInfo.CustomerPhoneNumber
     *
     * @mbg.generated
     */
    public void setCustomerphonenumber(String customerphonenumber) {
        this.customerphonenumber = customerphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerAddress
     *
     * @return the value of T_InsuranceContractInfo.CustomerAddress
     *
     * @mbg.generated
     */
    public String getCustomeraddress() {
        return customeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerAddress
     *
     * @param customeraddress the value for T_InsuranceContractInfo.CustomerAddress
     *
     * @mbg.generated
     */
    public void setCustomeraddress(String customeraddress) {
        this.customeraddress = customeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerEmail
     *
     * @return the value of T_InsuranceContractInfo.CustomerEmail
     *
     * @mbg.generated
     */
    public String getCustomeremail() {
        return customeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerEmail
     *
     * @param customeremail the value for T_InsuranceContractInfo.CustomerEmail
     *
     * @mbg.generated
     */
    public void setCustomeremail(String customeremail) {
        this.customeremail = customeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractDetail
     *
     * @return the value of T_InsuranceContractInfo.ContractDetail
     *
     * @mbg.generated
     */
    public String getContractdetail() {
        return contractdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractDetail
     *
     * @param contractdetail the value for T_InsuranceContractInfo.ContractDetail
     *
     * @mbg.generated
     */
    public void setContractdetail(String contractdetail) {
        this.contractdetail = contractdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractDate
     *
     * @return the value of T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    public String getContractdate() {
        return contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractDate
     *
     * @param contractdate the value for T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    public void setContractdate(String contractdate) {
        this.contractdate = contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.EmployeeId
     *
     * @return the value of T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.EmployeeId
     *
     * @param employeeid the value for T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InsurancecontractinfoWithBLOBs other = (InsurancecontractinfoWithBLOBs) that;
        return (this.getInsurancecompanyid() == null ? other.getInsurancecompanyid() == null : this.getInsurancecompanyid().equals(other.getInsurancecompanyid()))
            && (this.getInsurancecontractnumber() == null ? other.getInsurancecontractnumber() == null : this.getInsurancecontractnumber().equals(other.getInsurancecontractnumber()))
            && (this.getCustomersex() == null ? other.getCustomersex() == null : this.getCustomersex().equals(other.getCustomersex()))
            && (this.getContractamount() == null ? other.getContractamount() == null : this.getContractamount().equals(other.getContractamount()))
            && (this.getInsuranceplanname() == null ? other.getInsuranceplanname() == null : this.getInsuranceplanname().equals(other.getInsuranceplanname()))
            && (this.getCustomernamekana() == null ? other.getCustomernamekana() == null : this.getCustomernamekana().equals(other.getCustomernamekana()))
            && (this.getCustomername() == null ? other.getCustomername() == null : this.getCustomername().equals(other.getCustomername()))
            && (this.getRelationship() == null ? other.getRelationship() == null : this.getRelationship().equals(other.getRelationship()))
            && (this.getInsurednamekana() == null ? other.getInsurednamekana() == null : this.getInsurednamekana().equals(other.getInsurednamekana()))
            && (this.getInsuredname() == null ? other.getInsuredname() == null : this.getInsuredname().equals(other.getInsuredname()))
            && (this.getCustomerbirthday() == null ? other.getCustomerbirthday() == null : this.getCustomerbirthday().equals(other.getCustomerbirthday()))
            && (this.getCustomerphonenumber() == null ? other.getCustomerphonenumber() == null : this.getCustomerphonenumber().equals(other.getCustomerphonenumber()))
            && (this.getCustomeraddress() == null ? other.getCustomeraddress() == null : this.getCustomeraddress().equals(other.getCustomeraddress()))
            && (this.getCustomeremail() == null ? other.getCustomeremail() == null : this.getCustomeremail().equals(other.getCustomeremail()))
            && (this.getContractdetail() == null ? other.getContractdetail() == null : this.getContractdetail().equals(other.getContractdetail()))
            && (this.getContractdate() == null ? other.getContractdate() == null : this.getContractdate().equals(other.getContractdate()))
            && (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInsurancecompanyid() == null) ? 0 : getInsurancecompanyid().hashCode());
        result = prime * result + ((getInsurancecontractnumber() == null) ? 0 : getInsurancecontractnumber().hashCode());
        result = prime * result + ((getCustomersex() == null) ? 0 : getCustomersex().hashCode());
        result = prime * result + ((getContractamount() == null) ? 0 : getContractamount().hashCode());
        result = prime * result + ((getInsuranceplanname() == null) ? 0 : getInsuranceplanname().hashCode());
        result = prime * result + ((getCustomernamekana() == null) ? 0 : getCustomernamekana().hashCode());
        result = prime * result + ((getCustomername() == null) ? 0 : getCustomername().hashCode());
        result = prime * result + ((getRelationship() == null) ? 0 : getRelationship().hashCode());
        result = prime * result + ((getInsurednamekana() == null) ? 0 : getInsurednamekana().hashCode());
        result = prime * result + ((getInsuredname() == null) ? 0 : getInsuredname().hashCode());
        result = prime * result + ((getCustomerbirthday() == null) ? 0 : getCustomerbirthday().hashCode());
        result = prime * result + ((getCustomerphonenumber() == null) ? 0 : getCustomerphonenumber().hashCode());
        result = prime * result + ((getCustomeraddress() == null) ? 0 : getCustomeraddress().hashCode());
        result = prime * result + ((getCustomeremail() == null) ? 0 : getCustomeremail().hashCode());
        result = prime * result + ((getContractdetail() == null) ? 0 : getContractdetail().hashCode());
        result = prime * result + ((getContractdate() == null) ? 0 : getContractdate().hashCode());
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        return result;
    }
}
