package jp.co.siam.restapi.entity;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

public class Insurancecontractinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    @NotNull(message = "insurancecompanyid not null")
    private Integer insurancecompanyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceContractNumber
     *
     * @mbg.generated
     */
    @NotBlank(message = "insurancecontractnumber not null")
    private String insurancecontractnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CustomerSex
     *
     * @mbg.generated
     */
    private Integer customersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractAmount
     *
     * @mbg.generated
     */
    private Integer contractamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @return the value of T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public Integer getInsurancecompanyid() {
        return insurancecompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @param insurancecompanyid the value for T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public void setInsurancecompanyid(Integer insurancecompanyid) {
        this.insurancecompanyid = insurancecompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceContractNumber
     *
     * @return the value of T_InsuranceContractInfo.InsuranceContractNumber
     *
     * @mbg.generated
     */
    public String getInsurancecontractnumber() {
        return insurancecontractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceContractNumber
     *
     * @param insurancecontractnumber the value for T_InsuranceContractInfo.InsuranceContractNumber
     *
     * @mbg.generated
     */
    public void setInsurancecontractnumber(String insurancecontractnumber) {
        this.insurancecontractnumber = insurancecontractnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CustomerSex
     *
     * @return the value of T_InsuranceContractInfo.CustomerSex
     *
     * @mbg.generated
     */
    public Integer getCustomersex() {
        return customersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CustomerSex
     *
     * @param customersex the value for T_InsuranceContractInfo.CustomerSex
     *
     * @mbg.generated
     */
    public void setCustomersex(Integer customersex) {
        this.customersex = customersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractAmount
     *
     * @return the value of T_InsuranceContractInfo.ContractAmount
     *
     * @mbg.generated
     */
    public Integer getContractamount() {
        return contractamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractAmount
     *
     * @param contractamount the value for T_InsuranceContractInfo.ContractAmount
     *
     * @mbg.generated
     */
    public void setContractamount(Integer contractamount) {
        this.contractamount = contractamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Insurancecontractinfo other = (Insurancecontractinfo) that;
        return (this.getInsurancecompanyid() == null ? other.getInsurancecompanyid() == null : this.getInsurancecompanyid().equals(other.getInsurancecompanyid()))
            && (this.getInsurancecontractnumber() == null ? other.getInsurancecontractnumber() == null : this.getInsurancecontractnumber().equals(other.getInsurancecontractnumber()))
            && (this.getCustomersex() == null ? other.getCustomersex() == null : this.getCustomersex().equals(other.getCustomersex()))
            && (this.getContractamount() == null ? other.getContractamount() == null : this.getContractamount().equals(other.getContractamount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInsurancecompanyid() == null) ? 0 : getInsurancecompanyid().hashCode());
        result = prime * result + ((getInsurancecontractnumber() == null) ? 0 : getInsurancecontractnumber().hashCode());
        result = prime * result + ((getCustomersex() == null) ? 0 : getCustomersex().hashCode());
        result = prime * result + ((getContractamount() == null) ? 0 : getContractamount().hashCode());
        return result;
    }
}
