package jp.co.siam.restapi.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ApiModel("保険契約情報")
public class Insurancecontractinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceContractId
     *
     * @mbg.generated
     */
    @ApiModelProperty("保険契約Id")
    private Integer insurancecontractid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    @ApiModelProperty("保険会社Id")
    @NotBlank(message = "insurancecompanyidにnullはできません")
    private String insurancecompanyid;

    private String insurancecompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceProductId
     *
     * @mbg.generated
     */
    @ApiModelProperty("商品Id")
    private Integer insuranceproductid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsurancePapersNo
     *
     * @mbg.generated
     */
    @ApiModelProperty("証券番号")
    private String insurancepapersno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractorFamilyName
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者(姓)")
    @NotBlank(message = "contractorfamilynameにnullはできません")
    private String contractorfamilyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractorGivenName
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者(名)")
    @NotBlank(message = "contractorgivennameにnullはできません")
    private String contractorgivenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractorFamilyNameK
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者(セイ)")
    @NotBlank(message = "contractorfamilynamekにnullはできません")
    private String contractorfamilynamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractorGivenNameK
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者(メイ)")
    @NotBlank(message = "contractorgivennamekにnullはできません")
    private String contractorgivennamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約日")
    @NotNull(message = "contractdateにnullはできません")
    @JsonFormat(pattern="yyyy/MM/dd")
    private Date contractdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceStartDate
     *
     * @mbg.generated
     */
    @ApiModelProperty("保険開始日")
    @NotNull(message = "insurancestartdateにnullはできません")
    @JsonFormat(pattern="yyyy/MM/dd")
    private Date insurancestartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.IsCanceled
     *
     * @mbg.generated
     */
    @ApiModelProperty("解約フラグ")
    private Integer iscanceled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CancellationDate
     *
     * @mbg.generated
     */
    @ApiModelProperty("解約日")
    @JsonFormat(pattern="yyyy/MM/dd")
    private Date cancellationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuranceAmount
     *
     * @mbg.generated
     */
    @ApiModelProperty("保険金額")
    @NotNull(message = "insuranceamountにnullはできません")
    private Integer insuranceamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.PaymentCycle
     *
     * @mbg.generated
     */
    @ApiModelProperty("支払いサイクル")
    private Integer paymentcycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者との関係")
    @NotNull(message = "relationshipにnullはできません")
    private Integer relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.RelationshipOther
     *
     * @mbg.generated
     */
    @ApiModelProperty("契約者との関係(補足)")
    private String relationshipother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredPersonFamilyName
     *
     * @mbg.generated
     */
    @ApiModelProperty("被保険者(姓)")
    @NotBlank(message = "insuredpersonfamilynameにnullはできません")
    private String insuredpersonfamilyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredPersonGivenName
     *
     * @mbg.generated
     */
    @ApiModelProperty("被保険者(名)")
    @NotBlank(message = "insuredpersongivennameにnullはできません")
    private String insuredpersongivenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredPersonFamilyNameK
     *
     * @mbg.generated
     */
    @ApiModelProperty("被保険者(セイ)")
    @NotBlank(message = "insuredpersonfamilynamekにnullはできません")
    private String insuredpersonfamilynamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InsuredPersonGivenNameK
     *
     * @mbg.generated
     */
    @ApiModelProperty("被保険者(メイ)")
    @NotBlank(message = "insuredpersongivennamekにnullはできません")
    private String insuredpersongivennamek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Sex
     *
     * @mbg.generated
     */
    @ApiModelProperty("性別")
    @NotNull(message = "sexにnullはできません")
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.PhoneNumber
     *
     * @mbg.generated
     */
    @ApiModelProperty("電話番号")
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Email
     *
     * @mbg.generated
     */
    @ApiModelProperty("メール")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Birthday
     *
     * @mbg.generated
     */
    @ApiModelProperty("生年月日")
    @JsonFormat(pattern="yyyy/MM/dd")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Age
     *
     * @mbg.generated
     */
    @ApiModelProperty("年齢(保険開始時)")
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.AddressPostCode
     *
     * @mbg.generated
     */
    @ApiModelProperty("住所(郵便番号)")
    private String addresspostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    @ApiModelProperty("住所(都道府県)")
    private String addressprefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    @ApiModelProperty("住所(市区町村)")
    private String addressmunicipalities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.AddressOther
     *
     * @mbg.generated
     */
    @ApiModelProperty("住所(番地以降)")
    private String addressother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.Remarks
     *
     * @mbg.generated
     */
    @ApiModelProperty("備考")
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    @ApiModelProperty("社員番号")
    @NotBlank(message = "employeeidにnullはできません")
    private String employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.TeamEmployeeId
     *
     * @mbg.generated
     */
    @ApiModelProperty("共同募集社員番号")
    private String teamemployeeid;


    private String employeeName;

    private String teamemployeeName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.InitialCommission
     *
     * @mbg.generated
     */
    @ApiModelProperty("初年度手数料")
    @NotNull(message = "initialcommissionにnullはできません")
    private Integer initialcommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.PaymentMethod
     *
     * @mbg.generated
     */
    @ApiModelProperty("支給方式")
    @NotNull(message = "paymentmethodにnullはできません")
    private Integer paymentmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.PaymentMonths
     *
     * @mbg.generated
     */
    @ApiModelProperty("支給月数")
    private Integer paymentmonths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.TotalAmount
     *
     * @mbg.generated
     */
    @ApiModelProperty("総額")
    private Integer totalamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.PaymentPercentage
     *
     * @mbg.generated
     */
    @ApiModelProperty("支給比率")
    private Float paymentpercentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.DeleteFlag
     *
     * @mbg.generated
     */
    @ApiModelProperty("論理削除Flg")
    private Integer deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CreatedBy
     *
     * @mbg.generated
     */
    @ApiModelProperty("作成者")
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.CreatedDate
     *
     * @mbg.generated
     */
    @ApiModelProperty("作成日時")
    private Date createddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.UpdatedBy
     *
     * @mbg.generated
     */
    @ApiModelProperty("更新者")
    private String updatedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_InsuranceContractInfo.UpdatedDate
     *
     * @mbg.generated
     */
    @ApiModelProperty("更新日時")
    private Date updateddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceContractId
     *
     * @return the value of T_InsuranceContractInfo.InsuranceContractId
     *
     * @mbg.generated
     */
    public Integer getInsurancecontractid() {
        return insurancecontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceContractId
     *
     * @param insurancecontractid the value for T_InsuranceContractInfo.InsuranceContractId
     *
     * @mbg.generated
     */
    public void setInsurancecontractid(Integer insurancecontractid) {
        this.insurancecontractid = insurancecontractid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @return the value of T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public String getInsurancecompanyid() {
        return insurancecompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @param insurancecompanyid the value for T_InsuranceContractInfo.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public void setInsurancecompanyid(String insurancecompanyid) {
        this.insurancecompanyid = insurancecompanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceProductId
     *
     * @return the value of T_InsuranceContractInfo.InsuranceProductId
     *
     * @mbg.generated
     */
    public Integer getInsuranceproductid() {
        return insuranceproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceProductId
     *
     * @param insuranceproductid the value for T_InsuranceContractInfo.InsuranceProductId
     *
     * @mbg.generated
     */
    public void setInsuranceproductid(Integer insuranceproductid) {
        this.insuranceproductid = insuranceproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsurancePapersNo
     *
     * @return the value of T_InsuranceContractInfo.InsurancePapersNo
     *
     * @mbg.generated
     */
    public String getInsurancepapersno() {
        return insurancepapersno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsurancePapersNo
     *
     * @param insurancepapersno the value for T_InsuranceContractInfo.InsurancePapersNo
     *
     * @mbg.generated
     */
    public void setInsurancepapersno(String insurancepapersno) {
        this.insurancepapersno = insurancepapersno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractorFamilyName
     *
     * @return the value of T_InsuranceContractInfo.ContractorFamilyName
     *
     * @mbg.generated
     */
    public String getContractorfamilyname() {
        return contractorfamilyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractorFamilyName
     *
     * @param contractorfamilyname the value for T_InsuranceContractInfo.ContractorFamilyName
     *
     * @mbg.generated
     */
    public void setContractorfamilyname(String contractorfamilyname) {
        this.contractorfamilyname = contractorfamilyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractorGivenName
     *
     * @return the value of T_InsuranceContractInfo.ContractorGivenName
     *
     * @mbg.generated
     */
    public String getContractorgivenname() {
        return contractorgivenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractorGivenName
     *
     * @param contractorgivenname the value for T_InsuranceContractInfo.ContractorGivenName
     *
     * @mbg.generated
     */
    public void setContractorgivenname(String contractorgivenname) {
        this.contractorgivenname = contractorgivenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractorFamilyNameK
     *
     * @return the value of T_InsuranceContractInfo.ContractorFamilyNameK
     *
     * @mbg.generated
     */
    public String getContractorfamilynamek() {
        return contractorfamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractorFamilyNameK
     *
     * @param contractorfamilynamek the value for T_InsuranceContractInfo.ContractorFamilyNameK
     *
     * @mbg.generated
     */
    public void setContractorfamilynamek(String contractorfamilynamek) {
        this.contractorfamilynamek = contractorfamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractorGivenNameK
     *
     * @return the value of T_InsuranceContractInfo.ContractorGivenNameK
     *
     * @mbg.generated
     */
    public String getContractorgivennamek() {
        return contractorgivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractorGivenNameK
     *
     * @param contractorgivennamek the value for T_InsuranceContractInfo.ContractorGivenNameK
     *
     * @mbg.generated
     */
    public void setContractorgivennamek(String contractorgivennamek) {
        this.contractorgivennamek = contractorgivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.ContractDate
     *
     * @return the value of T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    public Date getContractdate() {
        return contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.ContractDate
     *
     * @param contractdate the value for T_InsuranceContractInfo.ContractDate
     *
     * @mbg.generated
     */
    public void setContractdate(Date contractdate) {
        this.contractdate = contractdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceStartDate
     *
     * @return the value of T_InsuranceContractInfo.InsuranceStartDate
     *
     * @mbg.generated
     */
    public Date getInsurancestartdate() {
        return insurancestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceStartDate
     *
     * @param insurancestartdate the value for T_InsuranceContractInfo.InsuranceStartDate
     *
     * @mbg.generated
     */
    public void setInsurancestartdate(Date insurancestartdate) {
        this.insurancestartdate = insurancestartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.IsCanceled
     *
     * @return the value of T_InsuranceContractInfo.IsCanceled
     *
     * @mbg.generated
     */
    public Integer getIscanceled() {
        return iscanceled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.IsCanceled
     *
     * @param iscanceled the value for T_InsuranceContractInfo.IsCanceled
     *
     * @mbg.generated
     */
    public void setIscanceled(Integer iscanceled) {
        this.iscanceled = iscanceled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CancellationDate
     *
     * @return the value of T_InsuranceContractInfo.CancellationDate
     *
     * @mbg.generated
     */
    public Date getCancellationdate() {
        return cancellationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CancellationDate
     *
     * @param cancellationdate the value for T_InsuranceContractInfo.CancellationDate
     *
     * @mbg.generated
     */
    public void setCancellationdate(Date cancellationdate) {
        this.cancellationdate = cancellationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuranceAmount
     *
     * @return the value of T_InsuranceContractInfo.InsuranceAmount
     *
     * @mbg.generated
     */
    public Integer getInsuranceamount() {
        return insuranceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuranceAmount
     *
     * @param insuranceamount the value for T_InsuranceContractInfo.InsuranceAmount
     *
     * @mbg.generated
     */
    public void setInsuranceamount(Integer insuranceamount) {
        this.insuranceamount = insuranceamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.PaymentCycle
     *
     * @return the value of T_InsuranceContractInfo.PaymentCycle
     *
     * @mbg.generated
     */
    public Integer getPaymentcycle() {
        return paymentcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.PaymentCycle
     *
     * @param paymentcycle the value for T_InsuranceContractInfo.PaymentCycle
     *
     * @mbg.generated
     */
    public void setPaymentcycle(Integer paymentcycle) {
        this.paymentcycle = paymentcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Relationship
     *
     * @return the value of T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    public Integer getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Relationship
     *
     * @param relationship the value for T_InsuranceContractInfo.Relationship
     *
     * @mbg.generated
     */
    public void setRelationship(Integer relationship) {
        this.relationship = relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.RelationshipOther
     *
     * @return the value of T_InsuranceContractInfo.RelationshipOther
     *
     * @mbg.generated
     */
    public String getRelationshipother() {
        return relationshipother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.RelationshipOther
     *
     * @param relationshipother the value for T_InsuranceContractInfo.RelationshipOther
     *
     * @mbg.generated
     */
    public void setRelationshipother(String relationshipother) {
        this.relationshipother = relationshipother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredPersonFamilyName
     *
     * @return the value of T_InsuranceContractInfo.InsuredPersonFamilyName
     *
     * @mbg.generated
     */
    public String getInsuredpersonfamilyname() {
        return insuredpersonfamilyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredPersonFamilyName
     *
     * @param insuredpersonfamilyname the value for T_InsuranceContractInfo.InsuredPersonFamilyName
     *
     * @mbg.generated
     */
    public void setInsuredpersonfamilyname(String insuredpersonfamilyname) {
        this.insuredpersonfamilyname = insuredpersonfamilyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredPersonGivenName
     *
     * @return the value of T_InsuranceContractInfo.InsuredPersonGivenName
     *
     * @mbg.generated
     */
    public String getInsuredpersongivenname() {
        return insuredpersongivenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredPersonGivenName
     *
     * @param insuredpersongivenname the value for T_InsuranceContractInfo.InsuredPersonGivenName
     *
     * @mbg.generated
     */
    public void setInsuredpersongivenname(String insuredpersongivenname) {
        this.insuredpersongivenname = insuredpersongivenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredPersonFamilyNameK
     *
     * @return the value of T_InsuranceContractInfo.InsuredPersonFamilyNameK
     *
     * @mbg.generated
     */
    public String getInsuredpersonfamilynamek() {
        return insuredpersonfamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredPersonFamilyNameK
     *
     * @param insuredpersonfamilynamek the value for T_InsuranceContractInfo.InsuredPersonFamilyNameK
     *
     * @mbg.generated
     */
    public void setInsuredpersonfamilynamek(String insuredpersonfamilynamek) {
        this.insuredpersonfamilynamek = insuredpersonfamilynamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InsuredPersonGivenNameK
     *
     * @return the value of T_InsuranceContractInfo.InsuredPersonGivenNameK
     *
     * @mbg.generated
     */
    public String getInsuredpersongivennamek() {
        return insuredpersongivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InsuredPersonGivenNameK
     *
     * @param insuredpersongivennamek the value for T_InsuranceContractInfo.InsuredPersonGivenNameK
     *
     * @mbg.generated
     */
    public void setInsuredpersongivennamek(String insuredpersongivennamek) {
        this.insuredpersongivennamek = insuredpersongivennamek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Sex
     *
     * @return the value of T_InsuranceContractInfo.Sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Sex
     *
     * @param sex the value for T_InsuranceContractInfo.Sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.PhoneNumber
     *
     * @return the value of T_InsuranceContractInfo.PhoneNumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.PhoneNumber
     *
     * @param phonenumber the value for T_InsuranceContractInfo.PhoneNumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Email
     *
     * @return the value of T_InsuranceContractInfo.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Email
     *
     * @param email the value for T_InsuranceContractInfo.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Birthday
     *
     * @return the value of T_InsuranceContractInfo.Birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Birthday
     *
     * @param birthday the value for T_InsuranceContractInfo.Birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Age
     *
     * @return the value of T_InsuranceContractInfo.Age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Age
     *
     * @param age the value for T_InsuranceContractInfo.Age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.AddressPostCode
     *
     * @return the value of T_InsuranceContractInfo.AddressPostCode
     *
     * @mbg.generated
     */
    public String getAddresspostcode() {
        return addresspostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.AddressPostCode
     *
     * @param addresspostcode the value for T_InsuranceContractInfo.AddressPostCode
     *
     * @mbg.generated
     */
    public void setAddresspostcode(String addresspostcode) {
        this.addresspostcode = addresspostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.AddressPrefecture
     *
     * @return the value of T_InsuranceContractInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    public String getAddressprefecture() {
        return addressprefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.AddressPrefecture
     *
     * @param addressprefecture the value for T_InsuranceContractInfo.AddressPrefecture
     *
     * @mbg.generated
     */
    public void setAddressprefecture(String addressprefecture) {
        this.addressprefecture = addressprefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.AddressMunicipalities
     *
     * @return the value of T_InsuranceContractInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    public String getAddressmunicipalities() {
        return addressmunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.AddressMunicipalities
     *
     * @param addressmunicipalities the value for T_InsuranceContractInfo.AddressMunicipalities
     *
     * @mbg.generated
     */
    public void setAddressmunicipalities(String addressmunicipalities) {
        this.addressmunicipalities = addressmunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.AddressOther
     *
     * @return the value of T_InsuranceContractInfo.AddressOther
     *
     * @mbg.generated
     */
    public String getAddressother() {
        return addressother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.AddressOther
     *
     * @param addressother the value for T_InsuranceContractInfo.AddressOther
     *
     * @mbg.generated
     */
    public void setAddressother(String addressother) {
        this.addressother = addressother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.Remarks
     *
     * @return the value of T_InsuranceContractInfo.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.Remarks
     *
     * @param remarks the value for T_InsuranceContractInfo.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.EmployeeId
     *
     * @return the value of T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.EmployeeId
     *
     * @param employeeid the value for T_InsuranceContractInfo.EmployeeId
     *
     * @mbg.generated
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.TeamEmployeeId
     *
     * @return the value of T_InsuranceContractInfo.TeamEmployeeId
     *
     * @mbg.generated
     */
    public String getTeamemployeeid() {
        return teamemployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.TeamEmployeeId
     *
     * @param teamemployeeid the value for T_InsuranceContractInfo.TeamEmployeeId
     *
     * @mbg.generated
     */
    public void setTeamemployeeid(String teamemployeeid) {
        this.teamemployeeid = teamemployeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.InitialCommission
     *
     * @return the value of T_InsuranceContractInfo.InitialCommission
     *
     * @mbg.generated
     */
    public Integer getInitialcommission() {
        return initialcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.InitialCommission
     *
     * @param initialcommission the value for T_InsuranceContractInfo.InitialCommission
     *
     * @mbg.generated
     */
    public void setInitialcommission(Integer initialcommission) {
        this.initialcommission = initialcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.PaymentMethod
     *
     * @return the value of T_InsuranceContractInfo.PaymentMethod
     *
     * @mbg.generated
     */
    public Integer getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.PaymentMethod
     *
     * @param paymentmethod the value for T_InsuranceContractInfo.PaymentMethod
     *
     * @mbg.generated
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.PaymentMonths
     *
     * @return the value of T_InsuranceContractInfo.PaymentMonths
     *
     * @mbg.generated
     */
    public Integer getPaymentmonths() {
        return paymentmonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.PaymentMonths
     *
     * @param paymentmonths the value for T_InsuranceContractInfo.PaymentMonths
     *
     * @mbg.generated
     */
    public void setPaymentmonths(Integer paymentmonths) {
        this.paymentmonths = paymentmonths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.TotalAmount
     *
     * @return the value of T_InsuranceContractInfo.TotalAmount
     *
     * @mbg.generated
     */
    public Integer getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.TotalAmount
     *
     * @param totalamount the value for T_InsuranceContractInfo.TotalAmount
     *
     * @mbg.generated
     */
    public void setTotalamount(Integer totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.PaymentPercentage
     *
     * @return the value of T_InsuranceContractInfo.PaymentPercentage
     *
     * @mbg.generated
     */
    public Float getPaymentpercentage() {
        return paymentpercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.PaymentPercentage
     *
     * @param paymentpercentage the value for T_InsuranceContractInfo.PaymentPercentage
     *
     * @mbg.generated
     */
    public void setPaymentpercentage(Float paymentpercentage) {
        this.paymentpercentage = paymentpercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.DeleteFlag
     *
     * @return the value of T_InsuranceContractInfo.DeleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.DeleteFlag
     *
     * @param deleteflag the value for T_InsuranceContractInfo.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CreatedBy
     *
     * @return the value of T_InsuranceContractInfo.CreatedBy
     *
     * @mbg.generated
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CreatedBy
     *
     * @param createdby the value for T_InsuranceContractInfo.CreatedBy
     *
     * @mbg.generated
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.CreatedDate
     *
     * @return the value of T_InsuranceContractInfo.CreatedDate
     *
     * @mbg.generated
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.CreatedDate
     *
     * @param createddate the value for T_InsuranceContractInfo.CreatedDate
     *
     * @mbg.generated
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.UpdatedBy
     *
     * @return the value of T_InsuranceContractInfo.UpdatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.UpdatedBy
     *
     * @param updatedby the value for T_InsuranceContractInfo.UpdatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_InsuranceContractInfo.UpdatedDate
     *
     * @return the value of T_InsuranceContractInfo.UpdatedDate
     *
     * @mbg.generated
     */
    public Date getUpdateddate() {
        return updateddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_InsuranceContractInfo.UpdatedDate
     *
     * @param updateddate the value for T_InsuranceContractInfo.UpdatedDate
     *
     * @mbg.generated
     */
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getTeamemployeeName() {
        return teamemployeeName;
    }

    public void setTeamemployeeName(String teamemployeeName) {
        this.teamemployeeName = teamemployeeName;
    }

    public String getInsurancecompanyName() {
        return insurancecompanyName;
    }

    public void setInsurancecompanyName(String insurancecompanyName) {
        this.insurancecompanyName = insurancecompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Insurancecontractinfo other = (Insurancecontractinfo) that;
        return (this.getInsurancecontractid() == null ? other.getInsurancecontractid() == null : this.getInsurancecontractid().equals(other.getInsurancecontractid()))
            && (this.getInsurancecompanyid() == null ? other.getInsurancecompanyid() == null : this.getInsurancecompanyid().equals(other.getInsurancecompanyid()))
            && (this.getInsuranceproductid() == null ? other.getInsuranceproductid() == null : this.getInsuranceproductid().equals(other.getInsuranceproductid()))
            && (this.getInsurancepapersno() == null ? other.getInsurancepapersno() == null : this.getInsurancepapersno().equals(other.getInsurancepapersno()))
            && (this.getContractorfamilyname() == null ? other.getContractorfamilyname() == null : this.getContractorfamilyname().equals(other.getContractorfamilyname()))
            && (this.getContractorgivenname() == null ? other.getContractorgivenname() == null : this.getContractorgivenname().equals(other.getContractorgivenname()))
            && (this.getContractorfamilynamek() == null ? other.getContractorfamilynamek() == null : this.getContractorfamilynamek().equals(other.getContractorfamilynamek()))
            && (this.getContractorgivennamek() == null ? other.getContractorgivennamek() == null : this.getContractorgivennamek().equals(other.getContractorgivennamek()))
            && (this.getContractdate() == null ? other.getContractdate() == null : this.getContractdate().equals(other.getContractdate()))
            && (this.getInsurancestartdate() == null ? other.getInsurancestartdate() == null : this.getInsurancestartdate().equals(other.getInsurancestartdate()))
            && (this.getIscanceled() == null ? other.getIscanceled() == null : this.getIscanceled().equals(other.getIscanceled()))
            && (this.getCancellationdate() == null ? other.getCancellationdate() == null : this.getCancellationdate().equals(other.getCancellationdate()))
            && (this.getInsuranceamount() == null ? other.getInsuranceamount() == null : this.getInsuranceamount().equals(other.getInsuranceamount()))
            && (this.getPaymentcycle() == null ? other.getPaymentcycle() == null : this.getPaymentcycle().equals(other.getPaymentcycle()))
            && (this.getRelationship() == null ? other.getRelationship() == null : this.getRelationship().equals(other.getRelationship()))
            && (this.getRelationshipother() == null ? other.getRelationshipother() == null : this.getRelationshipother().equals(other.getRelationshipother()))
            && (this.getInsuredpersonfamilyname() == null ? other.getInsuredpersonfamilyname() == null : this.getInsuredpersonfamilyname().equals(other.getInsuredpersonfamilyname()))
            && (this.getInsuredpersongivenname() == null ? other.getInsuredpersongivenname() == null : this.getInsuredpersongivenname().equals(other.getInsuredpersongivenname()))
            && (this.getInsuredpersonfamilynamek() == null ? other.getInsuredpersonfamilynamek() == null : this.getInsuredpersonfamilynamek().equals(other.getInsuredpersonfamilynamek()))
            && (this.getInsuredpersongivennamek() == null ? other.getInsuredpersongivennamek() == null : this.getInsuredpersongivennamek().equals(other.getInsuredpersongivennamek()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getPhonenumber() == null ? other.getPhonenumber() == null : this.getPhonenumber().equals(other.getPhonenumber()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getAddresspostcode() == null ? other.getAddresspostcode() == null : this.getAddresspostcode().equals(other.getAddresspostcode()))
            && (this.getAddressprefecture() == null ? other.getAddressprefecture() == null : this.getAddressprefecture().equals(other.getAddressprefecture()))
            && (this.getAddressmunicipalities() == null ? other.getAddressmunicipalities() == null : this.getAddressmunicipalities().equals(other.getAddressmunicipalities()))
            && (this.getAddressother() == null ? other.getAddressother() == null : this.getAddressother().equals(other.getAddressother()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getEmployeeid() == null ? other.getEmployeeid() == null : this.getEmployeeid().equals(other.getEmployeeid()))
            && (this.getTeamemployeeid() == null ? other.getTeamemployeeid() == null : this.getTeamemployeeid().equals(other.getTeamemployeeid()))
            && (this.getInitialcommission() == null ? other.getInitialcommission() == null : this.getInitialcommission().equals(other.getInitialcommission()))
            && (this.getPaymentmethod() == null ? other.getPaymentmethod() == null : this.getPaymentmethod().equals(other.getPaymentmethod()))
            && (this.getPaymentmonths() == null ? other.getPaymentmonths() == null : this.getPaymentmonths().equals(other.getPaymentmonths()))
            && (this.getTotalamount() == null ? other.getTotalamount() == null : this.getTotalamount().equals(other.getTotalamount()))
            && (this.getPaymentpercentage() == null ? other.getPaymentpercentage() == null : this.getPaymentpercentage().equals(other.getPaymentpercentage()))
            && (this.getDeleteflag() == null ? other.getDeleteflag() == null : this.getDeleteflag().equals(other.getDeleteflag()))
            && (this.getCreatedby() == null ? other.getCreatedby() == null : this.getCreatedby().equals(other.getCreatedby()))
            && (this.getCreateddate() == null ? other.getCreateddate() == null : this.getCreateddate().equals(other.getCreateddate()))
            && (this.getUpdatedby() == null ? other.getUpdatedby() == null : this.getUpdatedby().equals(other.getUpdatedby()))
            && (this.getUpdateddate() == null ? other.getUpdateddate() == null : this.getUpdateddate().equals(other.getUpdateddate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInsurancecontractid() == null) ? 0 : getInsurancecontractid().hashCode());
        result = prime * result + ((getInsurancecompanyid() == null) ? 0 : getInsurancecompanyid().hashCode());
        result = prime * result + ((getInsuranceproductid() == null) ? 0 : getInsuranceproductid().hashCode());
        result = prime * result + ((getInsurancepapersno() == null) ? 0 : getInsurancepapersno().hashCode());
        result = prime * result + ((getContractorfamilyname() == null) ? 0 : getContractorfamilyname().hashCode());
        result = prime * result + ((getContractorgivenname() == null) ? 0 : getContractorgivenname().hashCode());
        result = prime * result + ((getContractorfamilynamek() == null) ? 0 : getContractorfamilynamek().hashCode());
        result = prime * result + ((getContractorgivennamek() == null) ? 0 : getContractorgivennamek().hashCode());
        result = prime * result + ((getContractdate() == null) ? 0 : getContractdate().hashCode());
        result = prime * result + ((getInsurancestartdate() == null) ? 0 : getInsurancestartdate().hashCode());
        result = prime * result + ((getIscanceled() == null) ? 0 : getIscanceled().hashCode());
        result = prime * result + ((getCancellationdate() == null) ? 0 : getCancellationdate().hashCode());
        result = prime * result + ((getInsuranceamount() == null) ? 0 : getInsuranceamount().hashCode());
        result = prime * result + ((getPaymentcycle() == null) ? 0 : getPaymentcycle().hashCode());
        result = prime * result + ((getRelationship() == null) ? 0 : getRelationship().hashCode());
        result = prime * result + ((getRelationshipother() == null) ? 0 : getRelationshipother().hashCode());
        result = prime * result + ((getInsuredpersonfamilyname() == null) ? 0 : getInsuredpersonfamilyname().hashCode());
        result = prime * result + ((getInsuredpersongivenname() == null) ? 0 : getInsuredpersongivenname().hashCode());
        result = prime * result + ((getInsuredpersonfamilynamek() == null) ? 0 : getInsuredpersonfamilynamek().hashCode());
        result = prime * result + ((getInsuredpersongivennamek() == null) ? 0 : getInsuredpersongivennamek().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getPhonenumber() == null) ? 0 : getPhonenumber().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getAddresspostcode() == null) ? 0 : getAddresspostcode().hashCode());
        result = prime * result + ((getAddressprefecture() == null) ? 0 : getAddressprefecture().hashCode());
        result = prime * result + ((getAddressmunicipalities() == null) ? 0 : getAddressmunicipalities().hashCode());
        result = prime * result + ((getAddressother() == null) ? 0 : getAddressother().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getEmployeeid() == null) ? 0 : getEmployeeid().hashCode());
        result = prime * result + ((getTeamemployeeid() == null) ? 0 : getTeamemployeeid().hashCode());
        result = prime * result + ((getInitialcommission() == null) ? 0 : getInitialcommission().hashCode());
        result = prime * result + ((getPaymentmethod() == null) ? 0 : getPaymentmethod().hashCode());
        result = prime * result + ((getPaymentmonths() == null) ? 0 : getPaymentmonths().hashCode());
        result = prime * result + ((getTotalamount() == null) ? 0 : getTotalamount().hashCode());
        result = prime * result + ((getPaymentpercentage() == null) ? 0 : getPaymentpercentage().hashCode());
        result = prime * result + ((getDeleteflag() == null) ? 0 : getDeleteflag().hashCode());
        result = prime * result + ((getCreatedby() == null) ? 0 : getCreatedby().hashCode());
        result = prime * result + ((getCreateddate() == null) ? 0 : getCreateddate().hashCode());
        result = prime * result + ((getUpdatedby() == null) ? 0 : getUpdatedby().hashCode());
        result = prime * result + ((getUpdateddate() == null) ? 0 : getUpdateddate().hashCode());
        return result;
    }
}
