package jp.co.siam.restapi.entity;

import java.util.Date;

public class Insurancecompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.InsuranceCompanyId
     *
     * @mbg.generated
     */
    private String insuranceCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.InsuranceCompanyName
     *
     * @mbg.generated
     */
    private String insuranceCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.AddressPostCode
     *
     * @mbg.generated
     */
    private String addressPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.AddressPrefecture
     *
     * @mbg.generated
     */
    private String addressPrefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.AddressMunicipalities
     *
     * @mbg.generated
     */
    private String addressMunicipalities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.AddressOther
     *
     * @mbg.generated
     */
    private String addressOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.InChargeId
     *
     * @mbg.generated
     */
    private Integer inChargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.Remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.DeleteFlag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.CreatedBy
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.CreatedDate
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.UpdatedBy
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column M_InsuranceCompany.UpdatedDate
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.InsuranceCompanyId
     *
     * @return the value of M_InsuranceCompany.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public String getInsuranceCompanyId() {
        return insuranceCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.InsuranceCompanyId
     *
     * @param insuranceCompanyId the value for M_InsuranceCompany.InsuranceCompanyId
     *
     * @mbg.generated
     */
    public void setInsuranceCompanyId(String insuranceCompanyId) {
        this.insuranceCompanyId = insuranceCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.InsuranceCompanyName
     *
     * @return the value of M_InsuranceCompany.InsuranceCompanyName
     *
     * @mbg.generated
     */
    public String getInsuranceCompanyName() {
        return insuranceCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.InsuranceCompanyName
     *
     * @param insuranceCompanyName the value for M_InsuranceCompany.InsuranceCompanyName
     *
     * @mbg.generated
     */
    public void setInsuranceCompanyName(String insuranceCompanyName) {
        this.insuranceCompanyName = insuranceCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.AddressPostCode
     *
     * @return the value of M_InsuranceCompany.AddressPostCode
     *
     * @mbg.generated
     */
    public String getAddressPostCode() {
        return addressPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.AddressPostCode
     *
     * @param addressPostCode the value for M_InsuranceCompany.AddressPostCode
     *
     * @mbg.generated
     */
    public void setAddressPostCode(String addressPostCode) {
        this.addressPostCode = addressPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.AddressPrefecture
     *
     * @return the value of M_InsuranceCompany.AddressPrefecture
     *
     * @mbg.generated
     */
    public String getAddressPrefecture() {
        return addressPrefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.AddressPrefecture
     *
     * @param addressPrefecture the value for M_InsuranceCompany.AddressPrefecture
     *
     * @mbg.generated
     */
    public void setAddressPrefecture(String addressPrefecture) {
        this.addressPrefecture = addressPrefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.AddressMunicipalities
     *
     * @return the value of M_InsuranceCompany.AddressMunicipalities
     *
     * @mbg.generated
     */
    public String getAddressMunicipalities() {
        return addressMunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.AddressMunicipalities
     *
     * @param addressMunicipalities the value for M_InsuranceCompany.AddressMunicipalities
     *
     * @mbg.generated
     */
    public void setAddressMunicipalities(String addressMunicipalities) {
        this.addressMunicipalities = addressMunicipalities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.AddressOther
     *
     * @return the value of M_InsuranceCompany.AddressOther
     *
     * @mbg.generated
     */
    public String getAddressOther() {
        return addressOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.AddressOther
     *
     * @param addressOther the value for M_InsuranceCompany.AddressOther
     *
     * @mbg.generated
     */
    public void setAddressOther(String addressOther) {
        this.addressOther = addressOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.InChargeId
     *
     * @return the value of M_InsuranceCompany.InChargeId
     *
     * @mbg.generated
     */
    public Integer getInChargeId() {
        return inChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.InChargeId
     *
     * @param inChargeId the value for M_InsuranceCompany.InChargeId
     *
     * @mbg.generated
     */
    public void setInChargeId(Integer inChargeId) {
        this.inChargeId = inChargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.Remarks
     *
     * @return the value of M_InsuranceCompany.Remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.Remarks
     *
     * @param remarks the value for M_InsuranceCompany.Remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.DeleteFlag
     *
     * @return the value of M_InsuranceCompany.DeleteFlag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.DeleteFlag
     *
     * @param deleteFlag the value for M_InsuranceCompany.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.CreatedBy
     *
     * @return the value of M_InsuranceCompany.CreatedBy
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.CreatedBy
     *
     * @param createdBy the value for M_InsuranceCompany.CreatedBy
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.CreatedDate
     *
     * @return the value of M_InsuranceCompany.CreatedDate
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.CreatedDate
     *
     * @param createdDate the value for M_InsuranceCompany.CreatedDate
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.UpdatedBy
     *
     * @return the value of M_InsuranceCompany.UpdatedBy
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.UpdatedBy
     *
     * @param updatedBy the value for M_InsuranceCompany.UpdatedBy
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column M_InsuranceCompany.UpdatedDate
     *
     * @return the value of M_InsuranceCompany.UpdatedDate
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column M_InsuranceCompany.UpdatedDate
     *
     * @param updatedDate the value for M_InsuranceCompany.UpdatedDate
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Insurancecompany other = (Insurancecompany) that;
        return (this.getInsuranceCompanyId() == null ? other.getInsuranceCompanyId() == null : this.getInsuranceCompanyId().equals(other.getInsuranceCompanyId()))
            && (this.getInsuranceCompanyName() == null ? other.getInsuranceCompanyName() == null : this.getInsuranceCompanyName().equals(other.getInsuranceCompanyName()))
            && (this.getAddressPostCode() == null ? other.getAddressPostCode() == null : this.getAddressPostCode().equals(other.getAddressPostCode()))
            && (this.getAddressPrefecture() == null ? other.getAddressPrefecture() == null : this.getAddressPrefecture().equals(other.getAddressPrefecture()))
            && (this.getAddressMunicipalities() == null ? other.getAddressMunicipalities() == null : this.getAddressMunicipalities().equals(other.getAddressMunicipalities()))
            && (this.getAddressOther() == null ? other.getAddressOther() == null : this.getAddressOther().equals(other.getAddressOther()))
            && (this.getInChargeId() == null ? other.getInChargeId() == null : this.getInChargeId().equals(other.getInChargeId()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInsuranceCompanyId() == null) ? 0 : getInsuranceCompanyId().hashCode());
        result = prime * result + ((getInsuranceCompanyName() == null) ? 0 : getInsuranceCompanyName().hashCode());
        result = prime * result + ((getAddressPostCode() == null) ? 0 : getAddressPostCode().hashCode());
        result = prime * result + ((getAddressPrefecture() == null) ? 0 : getAddressPrefecture().hashCode());
        result = prime * result + ((getAddressMunicipalities() == null) ? 0 : getAddressMunicipalities().hashCode());
        result = prime * result + ((getAddressOther() == null) ? 0 : getAddressOther().hashCode());
        result = prime * result + ((getInChargeId() == null) ? 0 : getInChargeId().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        return result;
    }
}