package jp.co.siam.restapi.entity;

import java.util.ArrayList;
import java.util.List;

public class InsurancecontractinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public InsurancecontractinfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInsurancecompanyidIsNull() {
            addCriterion("InsuranceCompanyId is null");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidIsNotNull() {
            addCriterion("InsuranceCompanyId is not null");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidEqualTo(Integer value) {
            addCriterion("InsuranceCompanyId =", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidNotEqualTo(Integer value) {
            addCriterion("InsuranceCompanyId <>", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidGreaterThan(Integer value) {
            addCriterion("InsuranceCompanyId >", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("InsuranceCompanyId >=", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidLessThan(Integer value) {
            addCriterion("InsuranceCompanyId <", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidLessThanOrEqualTo(Integer value) {
            addCriterion("InsuranceCompanyId <=", value, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidIn(List<Integer> values) {
            addCriterion("InsuranceCompanyId in", values, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidNotIn(List<Integer> values) {
            addCriterion("InsuranceCompanyId not in", values, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidBetween(Integer value1, Integer value2) {
            addCriterion("InsuranceCompanyId between", value1, value2, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecompanyidNotBetween(Integer value1, Integer value2) {
            addCriterion("InsuranceCompanyId not between", value1, value2, "insurancecompanyid");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberIsNull() {
            addCriterion("InsuranceContractNumber is null");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberIsNotNull() {
            addCriterion("InsuranceContractNumber is not null");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberEqualTo(String value) {
            addCriterion("InsuranceContractNumber =", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberNotEqualTo(String value) {
            addCriterion("InsuranceContractNumber <>", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberGreaterThan(String value) {
            addCriterion("InsuranceContractNumber >", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberGreaterThanOrEqualTo(String value) {
            addCriterion("InsuranceContractNumber >=", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberLessThan(String value) {
            addCriterion("InsuranceContractNumber <", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberLessThanOrEqualTo(String value) {
            addCriterion("InsuranceContractNumber <=", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberLike(String value) {
            addCriterion("InsuranceContractNumber like", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberNotLike(String value) {
            addCriterion("InsuranceContractNumber not like", value, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberIn(List<String> values) {
            addCriterion("InsuranceContractNumber in", values, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberNotIn(List<String> values) {
            addCriterion("InsuranceContractNumber not in", values, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberBetween(String value1, String value2) {
            addCriterion("InsuranceContractNumber between", value1, value2, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andInsurancecontractnumberNotBetween(String value1, String value2) {
            addCriterion("InsuranceContractNumber not between", value1, value2, "insurancecontractnumber");
            return (Criteria) this;
        }

        public Criteria andCustomersexIsNull() {
            addCriterion("CustomerSex is null");
            return (Criteria) this;
        }

        public Criteria andCustomersexIsNotNull() {
            addCriterion("CustomerSex is not null");
            return (Criteria) this;
        }

        public Criteria andCustomersexEqualTo(Integer value) {
            addCriterion("CustomerSex =", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexNotEqualTo(Integer value) {
            addCriterion("CustomerSex <>", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexGreaterThan(Integer value) {
            addCriterion("CustomerSex >", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexGreaterThanOrEqualTo(Integer value) {
            addCriterion("CustomerSex >=", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexLessThan(Integer value) {
            addCriterion("CustomerSex <", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexLessThanOrEqualTo(Integer value) {
            addCriterion("CustomerSex <=", value, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexIn(List<Integer> values) {
            addCriterion("CustomerSex in", values, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexNotIn(List<Integer> values) {
            addCriterion("CustomerSex not in", values, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexBetween(Integer value1, Integer value2) {
            addCriterion("CustomerSex between", value1, value2, "customersex");
            return (Criteria) this;
        }

        public Criteria andCustomersexNotBetween(Integer value1, Integer value2) {
            addCriterion("CustomerSex not between", value1, value2, "customersex");
            return (Criteria) this;
        }

        public Criteria andContractamountIsNull() {
            addCriterion("ContractAmount is null");
            return (Criteria) this;
        }

        public Criteria andContractamountIsNotNull() {
            addCriterion("ContractAmount is not null");
            return (Criteria) this;
        }

        public Criteria andContractamountEqualTo(Integer value) {
            addCriterion("ContractAmount =", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountNotEqualTo(Integer value) {
            addCriterion("ContractAmount <>", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountGreaterThan(Integer value) {
            addCriterion("ContractAmount >", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ContractAmount >=", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountLessThan(Integer value) {
            addCriterion("ContractAmount <", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountLessThanOrEqualTo(Integer value) {
            addCriterion("ContractAmount <=", value, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountIn(List<Integer> values) {
            addCriterion("ContractAmount in", values, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountNotIn(List<Integer> values) {
            addCriterion("ContractAmount not in", values, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountBetween(Integer value1, Integer value2) {
            addCriterion("ContractAmount between", value1, value2, "contractamount");
            return (Criteria) this;
        }

        public Criteria andContractamountNotBetween(Integer value1, Integer value2) {
            addCriterion("ContractAmount not between", value1, value2, "contractamount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}