package jp.co.siam.restapi.dao;

import java.util.List;
import jp.co.siam.restapi.entity.Code;
import jp.co.siam.restapi.entity.CodeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    long countByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    int deleteByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    int insert(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    int insertSelective(Code record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    List<Code> selectByExample(CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Code record, @Param("example") CodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CODE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Code record, @Param("example") CodeExample example);
}