package jp.co.siam.restapi.dao;

import java.util.List;
import jp.co.siam.restapi.entity.Employeeinfo;
import jp.co.siam.restapi.entity.EmployeeinfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmployeeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    long countByExample(EmployeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    int insert(Employeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    int insertSelective(Employeeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    List<Employeeinfo> selectByExample(EmployeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Employeeinfo record, @Param("example") EmployeeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_EmployeeInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Employeeinfo record, @Param("example") EmployeeinfoExample example);
}