package jp.co.siam.restapi.dao;

import java.util.List;
import jp.co.siam.restapi.entity.Insurancecompany;
import jp.co.siam.restapi.entity.InsurancecompanyExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface InsurancecompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    long countByExample(InsurancecompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    int deleteByExample(InsurancecompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    int insert(Insurancecompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    int insertSelective(Insurancecompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    List<Insurancecompany> selectByExample(InsurancecompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Insurancecompany record, @Param("example") InsurancecompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceCompany
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Insurancecompany record, @Param("example") InsurancecompanyExample example);
}