package jp.co.siam.restapi.dao;

import java.util.List;
import jp.co.siam.restapi.entity.Insuranceproduct;
import jp.co.siam.restapi.entity.InsuranceproductExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface InsuranceproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    long countByExample(InsuranceproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    int deleteByExample(InsuranceproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    int insert(Insuranceproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    int insertSelective(Insuranceproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    List<Insuranceproduct> selectByExample(InsuranceproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Insuranceproduct record, @Param("example") InsuranceproductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_InsuranceProduct
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Insuranceproduct record, @Param("example") InsuranceproductExample example);
}