package jp.co.siam.restapi.dao;

import java.util.List;
import jp.co.siam.restapi.entity.Insurancecontractinfo;
import jp.co.siam.restapi.entity.InsurancecontractinfoExample;
import jp.co.siam.restapi.entity.InsurancecontractinfoFindParam;
import jp.co.siam.restapi.entity.InsurancecontractinfoWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface InsurancecontractinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    long countByExample(InsurancecontractinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int deleteByExample(InsurancecontractinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int insert(InsurancecontractinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int insertSelective(InsurancecontractinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    List<InsurancecontractinfoWithBLOBs> selectByExampleWithBLOBs(InsurancecontractinfoExample example);

    List<InsurancecontractinfoWithBLOBs> selectByFindParam(@Param("findParam") InsurancecontractinfoFindParam findParam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    List<Insurancecontractinfo> selectByExample(InsurancecontractinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InsurancecontractinfoWithBLOBs record, @Param("example") InsurancecontractinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") InsurancecontractinfoWithBLOBs record, @Param("example") InsurancecontractinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_InsuranceContractInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Insurancecontractinfo record, @Param("example") InsurancecontractinfoExample example);
}
